apiVersion: v1
kind: Service
metadata:
  name: {{ include "galaxy-mk2.fullname" . }}
  labels:
    {{- include "galaxy-mk2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "galaxy-mk2.selectorLabels" . | nindent 4 }}
